import sharp from 'sharp';
import { readdir, writeFile, mkdir, stat } from 'fs/promises';
import { join, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const ROOT = resolve(__dirname, '..');
const INPUT_DIR = join(ROOT, 'src/assets');
const OUTPUT_DIR = join(ROOT, 'public/images');
const MANIFEST_PATH = join(ROOT, 'src/generated/image-manifest.ts');

const BREAKPOINTS = [480, 768, 1440, 2048];
const FORMATS = {
  avif: { quality: 65 },
  webp: { quality: 75 },
};
const JPEG_QUALITY = 80;
const PLACEHOLDER_WIDTH = 32;

// Hash → descriptive name mapping
const NAME_MAP = {
  '53e4c01aafd680ca3373772f4de41ed78bef4b5e': 'creation-car-front',
  'fa2ef239635cbba91d39d5ea6baa3253817a8379': 'creation-aerial',
  '0c9f997e642ff11beed0c4cc77a706b9b7e09e39': 'creation-interior',
  'fb6588bbc9f12fd165a47d6c1b75f42198039374': 'creation-engine',
  '77e513a12e9d4c61f063e3e877cc5fc74a7b5e07': 'driver-calm-race',
  '42878b06df40db9893727e5fbb42a7bee05b2276': 'helmet-closeup',
  '3f72aec9eef52b9b5c4081a0c575d7b41463749c': 'driver-calm-standing',
  '267e44eb9afb6a4f89546eded2c398a025ca8f00': 'portrait-cinematic',
  '4251cb51f5ba829324dd7a8f1ad8d507b6efa3dc': 'helmet-dramatic',
  '7dd01bd50234e347faf1c985a4e884b0e8aba696': 'driver-fullbody',
  'd79f81633478e30718ea536e43d65c35d8b651d5': 'car-360-view',
};

async function processImage(filePath, fileName) {
  const hash = fileName.replace(/\.\w+$/, '');
  const name = NAME_MAP[hash] || hash;

  console.log(`  Processing: ${name} (${fileName})`);

  const image = sharp(filePath);
  const metadata = await image.metadata();
  const originalWidth = metadata.width;
  const originalHeight = metadata.height;

  const entry = {
    avif: {},
    webp: {},
    jpg: '',
    placeholder: '',
    width: originalWidth,
    height: originalHeight,
  };

  // Generate responsive sizes for each format
  for (const bp of BREAKPOINTS) {
    if (bp > originalWidth) continue;

    for (const [format, opts] of Object.entries(FORMATS)) {
      const outName = `${name}-${bp}.${format}`;
      const outPath = join(OUTPUT_DIR, outName);

      await sharp(filePath)
        .resize(bp, null, { withoutEnlargement: true })
        [format](opts)
        .toFile(outPath);

      entry[format][bp] = `/images/${outName}`;
    }
  }

  // JPEG fallback at 1440
  const jpgWidth = Math.min(1440, originalWidth);
  const jpgName = `${name}-${jpgWidth}.jpg`;
  await sharp(filePath)
    .resize(jpgWidth, null, { withoutEnlargement: true })
    .jpeg({ quality: JPEG_QUALITY })
    .toFile(join(OUTPUT_DIR, jpgName));
  entry.jpg = `/images/${jpgName}`;

  // LQIP placeholder
  const placeholderBuffer = await sharp(filePath)
    .resize(PLACEHOLDER_WIDTH, null, { withoutEnlargement: true })
    .webp({ quality: 20 })
    .toBuffer();
  entry.placeholder = `data:image/webp;base64,${placeholderBuffer.toString('base64')}`;

  return { name, entry };
}

async function main() {
  console.log('Optimizing images...\n');

  await mkdir(OUTPUT_DIR, { recursive: true });

  const files = (await readdir(INPUT_DIR)).filter(f => /\.(png|jpg|jpeg)$/i.test(f));

  if (files.length === 0) {
    console.log('No images found in src/assets/');
    return;
  }

  const manifest = {};
  let totalInputSize = 0;
  let totalOutputSize = 0;

  for (const file of files) {
    const filePath = join(INPUT_DIR, file);
    const inputStat = await stat(filePath);
    totalInputSize += inputStat.size;

    const { name, entry } = await processImage(filePath, file);
    manifest[name] = entry;
  }

  // Calculate output size
  const outputFiles = await readdir(OUTPUT_DIR);
  for (const f of outputFiles) {
    const s = await stat(join(OUTPUT_DIR, f));
    totalOutputSize += s.size;
  }

  // Write TypeScript manifest
  const tsContent = `// Auto-generated by scripts/optimize-images.mjs — do not edit
export interface ImageEntry {
  avif: Record<number, string>;
  webp: Record<number, string>;
  jpg: string;
  placeholder: string;
  width: number;
  height: number;
}

export const images: Record<string, ImageEntry> = ${JSON.stringify(manifest, null, 2)};
`;

  await writeFile(MANIFEST_PATH, tsContent, 'utf-8');

  const inputMB = (totalInputSize / (1024 * 1024)).toFixed(1);
  const outputMB = (totalOutputSize / (1024 * 1024)).toFixed(1);
  const reduction = (((totalInputSize - totalOutputSize) / totalInputSize) * 100).toFixed(0);

  console.log(`\nDone!`);
  console.log(`  Input:  ${inputMB} MB (${files.length} images)`);
  console.log(`  Output: ${outputMB} MB (${outputFiles.length} files)`);
  console.log(`  Reduction: ${reduction}%`);
  console.log(`  Manifest: ${MANIFEST_PATH}`);
}

main().catch(err => {
  console.error('Image optimization failed:', err);
  process.exit(1);
});
